name: Deploy to GitHub Pages

on:
  push:
    branches:
      - lex_test 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: GitHub Pages Publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update GitHub Pages"
          commit_options: '--no-verify --signoff'
          file_pattern: 'docs/**/*'
          repository: .
          skip_dirty_check: true    
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'
